In [1]:
import pandas as pd
pd.set_option('max_colwidth', None)

In [2]:
districts = pd.read_csv('district.csv.gz')
districts

,District,Zone,Mau,Holder,Khata,Khesra,Excel,district_code,sub_div_code,circle_code
0,कटिहार,9,741,275732,145247,494758,excel/ROR_कटिहार_20220807.xlsx,10,2,12
1,कटिहार,9,741,275732,145247,494758,excel/ROR_कटिहार_20220807.xlsx,10,2,11
2,कटिहार,9,741,275732,145247,494758,excel/ROR_कटिहार_20220807.xlsx,10,1,8
3,कटिहार,9,741,275732,145247,494758,excel/ROR_कटिहार_20220807.xlsx,10,3,15
4,भागलपुर,10,2035,607718,445120,1421033,excel/ROR_भागलपुर_20220807.xlsx,22,3,51
...,...,...,...,...,...,...,...,...,...,...
506,मधेपुरा,13,465,195115,187039,930544,excel/ROR_मधेपुरा_20220807.xlsx,11,1,9
507,मधेपुरा,13,465,195115,187039,930544,excel/ROR_मधेपुरा_20220807.xlsx,11,1,10
508,मधेपुरा,13,465,195115,187039,930544,excel/ROR_मधेपुरा_20220807.xlsx,11,1,12
509,मधेपुरा,13,465,195115,187039,930544,excel/ROR_मधेपुरा_20220807.xlsx,11,1,13
510,मधेपुरा,13,465,195115,187039,930544,excel/ROR_मधेपुरा_20220807.xlsx,11,2,4

In [3]:
accounts = pd.read_csv('account.csv.gz', nrows=100)
accounts

,Order,Ryot_Holder_Name,Father_Husband_Name,Account_Number,Khresra_Number,Record_of_Rights,Account_Holder_No,District,Sub_Division,Zone,Mauja
0,1,लालमुनी सिंह,रामसुन्‍दर सिंह,29,1/74,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=0pk0y0fa3lswwz1nc4zuyl3w&LHID=3101090651000032&KNo=29,3101090651000032,कैमूर,भभुआ,रामपुर [009],बिदेसरपुर [राजस्व थाना न.-0847]
1,2,तुलसी दूबे,इन्‍द्रदयाल दूबे,12,1,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=0pk0y0fa3lswwz1nc4zuyl3w&LHID=3101090651000013&KNo=12,3101090651000013,कैमूर,भभुआ,रामपुर [009],बिदेसरपुर [राजस्व थाना न.-0847]
2,3,राजेश्‍वर सिंह,कैलाश सिंह,29,1/74,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=0pk0y0fa3lswwz1nc4zuyl3w&LHID=3101090651000058&KNo=29,3101090651000058,कैमूर,भभुआ,रामपुर [009],बिदेसरपुर [राजस्व थाना न.-0847]
3,4,जितेन्‍द्र कुमार दूबे,स्‍व0 तलुकराम दूबे,22,2,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=0pk0y0fa3lswwz1nc4zuyl3w&LHID=3101090651000040&KNo=22,3101090651000040,कैमूर,भभुआ,रामपुर [009],बिदेसरपुर [राजस्व थाना न.-0847]
4,5,बदन दूबे,स्‍व0 कैलाश दूबे,2,3,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=0pk0y0fa3lswwz1nc4zuyl3w&LHID=3101090651000044&KNo=2,3101090651000044,कैमूर,भभुआ,रामपुर [009],बिदेसरपुर [राजस्व थाना न.-0847]
...,...,...,...,...,...,...,...,...,...,...,...
95,16,सत्‍येन्‍्द्र सिंह,डोमा सिंह,56,3,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=uc34fpcyw5m25pcd2edwkree&LHID=3101090670000199&KNo=56,3101090670000199,कैमूर,भभुआ,रामपुर [009],बखरम [राजस्व थाना न.-0866]
96,17,श्री दुसाध,भागा दुसाध,46,4,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=uc34fpcyw5m25pcd2edwkree&LHID=3101090670000047&KNo=46,3101090670000047,कैमूर,भभुआ,रामपुर [009],बखरम [राजस्व थाना न.-0866]
97,18,मिश्री दुसाध,माता दुसाध,59,5,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=uc34fpcyw5m25pcd2edwkree&LHID=3101090670000060&KNo=59,3101090670000060,कैमूर,भभुआ,रामपुर [009],बखरम [राजस्व थाना न.-0866]
98,19,नगीना,प्रयाग दूसाध,17,6,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=uc34fpcyw5m25pcd2edwkree&LHID=3101090670000017&KNo=17,3101090670000017,कैमूर,भभुआ,रामपुर [009],बखरम [राजस्व थाना न.-0866]
99,20,वारमती देवी,मिश्री दुसाध,17,6,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=uc34fpcyw5m25pcd2edwkree&LHID=3101090670000099&KNo=17,3101090670000099,कैमूर,भभुआ,रामपुर [009],बखरम [राजस्व थाना न.-0866]

In [4]:
accounts = pd.read_csv('account.csv.gz', usecols=['Account_Holder_No', 'Record_of_Rights'])
accounts

,Record_of_Rights,Account_Holder_No
0,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=0pk0y0fa3lswwz1nc4zuyl3w&LHID=3101090651000032&KNo=29,3101090651000032
1,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=0pk0y0fa3lswwz1nc4zuyl3w&LHID=3101090651000013&KNo=12,3101090651000013
2,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=0pk0y0fa3lswwz1nc4zuyl3w&LHID=3101090651000058&KNo=29,3101090651000058
3,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=0pk0y0fa3lswwz1nc4zuyl3w&LHID=3101090651000040&KNo=22,3101090651000040
4,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=0pk0y0fa3lswwz1nc4zuyl3w&LHID=3101090651000044&KNo=2,3101090651000044
...,...,...
29275112,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=w05kljlt21xaylkmfsov2axd&LHID=2203411371001509&KNo=912/2,2203411371001509
29275113,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=w05kljlt21xaylkmfsov2axd&LHID=2203411371000663&KNo=380,2203411371000663
29275114,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=w05kljlt21xaylkmfsov2axd&LHID=2203411371001934&KNo=1163,2203411371001934
29275115,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=w05kljlt21xaylkmfsov2axd&LHID=2203411371000411&KNo=227,2203411371000411
29275116,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=w05kljlt21xaylkmfsov2axd&LHID=2203411371002978&KNo=1773/5,2203411371002978

In [5]:
accounts['Record_of_Rights']

0               http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=0pk0y0fa3lswwz1nc4zuyl3w&LHID=3101090651000032&KNo=29
1               http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=0pk0y0fa3lswwz1nc4zuyl3w&LHID=3101090651000013&KNo=12
2               http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=0pk0y0fa3lswwz1nc4zuyl3w&LHID=3101090651000058&KNo=29
3               http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=0pk0y0fa3lswwz1nc4zuyl3w&LHID=3101090651000040&KNo=22
4                http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=0pk0y0fa3lswwz1nc4zuyl3w&LHID=3101090651000044&KNo=2
                                                                  ...
29275112     http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=w05kljlt21xaylkmfsov2axd&LHID=2203411371001509&KNo=912/2
29275113       http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=w05kljlt21xaylkmfsov2axd&LHID=2203411371000663&KNo=380
29275114      http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=w05kljlt21xaylkmfsov2axd&LHID=2203411371001934&KNo=1163
29275115       http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=w05kljlt21xaylkmfsov2axd&LHID=2203411371000411&KNo=227
29275116    http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=w05kljlt21xaylkmfsov2axd&LHID=2203411371002978&KNo=1773/5
Name: Record_of_Rights, Length: 29275117, dtype: object

In [6]:
accounts[accounts.Account_Holder_No==2203411371001934]

,Record_of_Rights,Account_Holder_No
428854,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=gszepijm0iztyv2ssjvyvxw5&LHID=2203411371001934&KNo=1163,2203411371001934
430518,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=d0aluvazi4j45v3tpvpgf0sf&LHID=2203411371001934&KNo=1163,2203411371001934
432203,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=amrbpcnyz1jqpm2eo4vrbeho&LHID=2203411371001934&KNo=1163,2203411371001934
432209,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=amrbpcnyz1jqpm2eo4vrbeho&LHID=2203411371001934&KNo=1163,2203411371001934
432212,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=amrbpcnyz1jqpm2eo4vrbeho&LHID=2203411371001934&KNo=1163,2203411371001934
432213,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=amrbpcnyz1jqpm2eo4vrbeho&LHID=2203411371001934&KNo=1163,2203411371001934
432228,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=amrbpcnyz1jqpm2eo4vrbeho&LHID=2203411371001934&KNo=1163,2203411371001934
433816,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=5dvm2wsl2odsxs3ywa2mm3pl&LHID=2203411371001934&KNo=1163,2203411371001934
29263570,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=edr3qycyjajssrltsva2dhpl&LHID=2203411371001934&KNo=1163,2203411371001934
29263571,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=edr3qycyjajssrltsva2dhpl&LHID=2203411371001934&KNo=1163,2203411371001934
29264682,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=uojul4accc0mmomoenlam0n2&LHID=2203411371001934&KNo=1163,2203411371001934
29264696,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=uojul4accc0mmomoenlam0n2&LHID=2203411371001934&KNo=1163,2203411371001934
29266434,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=ut2tujdut1oregknufginepu&LHID=2203411371001934&KNo=1163,2203411371001934
29269044,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=3d4vznbctufnrlfjouvtvk2e&LHID=2203411371001934&KNo=1163,2203411371001934
29275114,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=w05kljlt21xaylkmfsov2axd&LHID=2203411371001934&KNo=1163,2203411371001934

In [8]:
accounts.drop_duplicates(subset=['Account_Holder_No'], inplace=True)
accounts

,Record_of_Rights,Account_Holder_No
0,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=0pk0y0fa3lswwz1nc4zuyl3w&LHID=3101090651000032&KNo=29,3101090651000032
1,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=0pk0y0fa3lswwz1nc4zuyl3w&LHID=3101090651000013&KNo=12,3101090651000013
2,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=0pk0y0fa3lswwz1nc4zuyl3w&LHID=3101090651000058&KNo=29,3101090651000058
3,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=0pk0y0fa3lswwz1nc4zuyl3w&LHID=3101090651000040&KNo=22,3101090651000040
4,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=0pk0y0fa3lswwz1nc4zuyl3w&LHID=3101090651000044&KNo=2,3101090651000044
...,...,...
29275105,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=w05kljlt21xaylkmfsov2axd&LHID=2203411371003512&KNo=2088,2203411371003512
29275107,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=w05kljlt21xaylkmfsov2axd&LHID=2203411371000367&KNo=204/1,2203411371000367
29275109,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=w05kljlt21xaylkmfsov2axd&LHID=2203411371000433&KNo=235,2203411371000433
29275111,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=w05kljlt21xaylkmfsov2axd&LHID=2203411371002663&KNo=1597,2203411371002663
29275112,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=w05kljlt21xaylkmfsov2axd&LHID=2203411371001509&KNo=912/2,2203411371001509

In [9]:
accounts.to_csv('account_unique.csv.gz', index=False, compression='gzip')

In [2]:
rights = pd.read_csv('rights.csv.gz', nrows=10)
rights

,url,name_of_ryot,name_of_father,residence,jati,thana,district,anchal,village,khatadari,...,land_type,area_acre,area_decimal,area_hectare,dhakal_swaroop,lagaan,terms,gair_dakhildar,orders,jamabandi
0,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=0pk0y0fa3lswwz1nc4zuyl3w&LHID=3101090651000032&KNo=29,लालमुनी सिंह,रामसुन्‍दर सिंह,"बरली,,",NaN,राजस्व थाना नंबर: 847,(31) कैमूर,(9) रामपुर,(651) बिदेसरपुर,3101090651000032,...,धनहर,0,20.25,0,NaN,4.96,0,NaN,NaN,कैमी29/1
1,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=0pk0y0fa3lswwz1nc4zuyl3w&LHID=3101090651000013&KNo=12,तुलसी दूबे,इन्‍द्रदयाल दूबे,"बहेरी,,",ब्राम्‍हण,राजस्व थाना नंबर: 847,(31) कैमूर,(9) रामपुर,(651) बिदेसरपुर,3101090651000013,...,धनहर,3,62.00,0,NaN,45.65,0,NaN,NaN,कैमी12/1
2,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=0pk0y0fa3lswwz1nc4zuyl3w&LHID=3101090651000013&KNo=12,तुलसी दूबे,इन्‍द्रदयाल दूबे,"बहेरी,,",ब्राम्‍हण,राजस्व थाना नंबर: 847,(31) कैमूर,(9) रामपुर,(651) बिदेसरपुर,3101090651000013,...,भीठ,2,47.00,0,NaN,0.00,0,NaN,NaN,कैमी12/1
3,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=0pk0y0fa3lswwz1nc4zuyl3w&LHID=3101090651000058&KNo=29,राजेश्‍वर सिंह,कैलाश सिंह,"बरली,,",NaN,राजस्व थाना नंबर: 847,(31) कैमूर,(9) रामपुर,(651) बिदेसरपुर,3101090651000058,...,धनहर,0,20.50,0,अभ्युक्ति: दाखिल खारिज वाद संख्‍या-173/90-91,0.00,0,NaN,NaN,कैमी38/1
4,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=0pk0y0fa3lswwz1nc4zuyl3w&LHID=3101090651000040&KNo=22,जितेन्‍द्र कुमार दूबे,स्‍व0 तलुकराम दूबे,"बहेरी,,",ब्राम्‍हण,राजस्व थाना नंबर: 847,(31) कैमूर,(9) रामपुर,(651) बिदेसरपुर,3101090651000040,...,धनहर,2,70.00,0,NaN,27.00,0,NaN,NaN,कैमी17/2
5,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=0pk0y0fa3lswwz1nc4zuyl3w&LHID=3101090651000044&KNo=2,बदन दूबे,स्‍व0 कैलाश दूबे,"बहेरी,,",ब्राम्‍हण,राजस्व थाना नंबर: 847,(31) कैमूर,(9) रामपुर,(651) बिदेसरपुर,3101090651000044,...,धनहर,1,47.00,0,अभ्युक्ति: 1035/12-13,30.00,0,NaN,NaN,कैमी21/2
6,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=0pk0y0fa3lswwz1nc4zuyl3w&LHID=3101090651000064&KNo=2,कैलाश दूबे,करीमन दूबे,"बहेरी,,",ब्राम्‍हण,राजस्व थाना नंबर: 847,(31) कैमूर,(9) रामपुर,(651) बिदेसरपुर,3101090651000064,...,धनहर,2,71.50,0,अभ्युक्ति: 1035/12-13,27.00,0,NaN,NaN,कैमी23/2
7,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=0pk0y0fa3lswwz1nc4zuyl3w&LHID=3101090651000064&KNo=2,कैलाश दूबे,करीमन दूबे,"बहेरी,,",ब्राम्‍हण,राजस्व थाना नंबर: 847,(31) कैमूर,(9) रामपुर,(651) बिदेसरपुर,3101090651000064,...,भीठ,1,6.00,0,NaN,0.00,0,NaN,NaN,कैमी23/2
8,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=0pk0y0fa3lswwz1nc4zuyl3w&LHID=3101090651000064&KNo=2,कैलाश दूबे,करीमन दूबे,"बहेरी,,",ब्राम्‍हण,राजस्व थाना नंबर: 847,(31) कैमूर,(9) रामपुर,(651) बिदेसरपुर,3101090651000064,...,धनहर,0,68.00,0,NaN,0.00,0,NaN,NaN,कैमी0
9,http://land.bihar.gov.in/Ror/ViewRoRReportNew.aspx?SID=0pk0y0fa3lswwz1nc4zuyl3w&LHID=3101090651000065&KNo=2,श्रीमती शांति देवी,पति हीरा दूबे,"बहेरी,,",ब्राम्‍हण,राजस्व थाना नंबर: 847,(31) कैमूर,(9) रामपुर,(651) बिदेसरपुर,3101090651000065,...,धनहर,0,80.50,0,NaN,0.00,0,NaN,NaN,कैमी24/2

In [2]:
df = pd.read_csv('account_unique.csv.gz', usecols=['Account_Holder_No'])
df

         Account_Holder_No
0         3101090651000032
1         3101090651000013
2         3101090651000058
3         3101090651000040
4         3101090651000044
...                    ...
7859517   2203411371003512
7859518   2203411371000367
7859519   2203411371000433
7859520   2203411371002663
7859521   2203411371001509

[7859522 rows x 1 columns]

In [3]:
rdf = pd.read_csv('rights.csv.gz', usecols=['khatadari'])
rdf

<ipython-input-3-a9d5e348bc3b>:1: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  rdf = pd.read_csv('rights.csv.gz', usecols=['khatadari'])

                 khatadari
0         3101090651000032
1         3101090651000013
2         3101090651000013
3         3101090651000058
4         3101090651000040
...                    ...
26864935  2203411371003449
26864936  2203411371003449
26864937  2203411371000156
26864938  2203411371003373
26864939  2203411371003373

[26864940 rows x 1 columns]

In [30]:
import re

def get_ac_no(c):
    m = re.match('.*?LHID=(\d*).*', c)
    if m:
        return int(m.group(1))
    else:
        return 0

rdf = None

for i, df in enumerate(pd.read_csv('rights.csv.gz', chunksize=500000, usecols=['url', 'khatadari'])):
    df.loc[df.khatadari=='Label', 'khatadari'] = df.loc[df.khatadari=='Label', 'url'].apply(lambda c: get_ac_no(c))
    if rdf is None:
        rdf = df[['khatadari']].copy()
    else:
        rdf = pd.concat([rdf, df[['khatadari']].copy()])
    print(i)

0
1
2
3

<ipython-input-30-22995dd2d7fb>:12: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df in enumerate(pd.read_csv('rights.csv.gz', chunksize=500000, usecols=['url', 'khatadari'])):

4
5
6
7
8

<ipython-input-30-22995dd2d7fb>:12: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df in enumerate(pd.read_csv('rights.csv.gz', chunksize=500000, usecols=['url', 'khatadari'])):

9

<ipython-input-30-22995dd2d7fb>:12: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df in enumerate(pd.read_csv('rights.csv.gz', chunksize=500000, usecols=['url', 'khatadari'])):

10

<ipython-input-30-22995dd2d7fb>:12: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df in enumerate(pd.read_csv('rights.csv.gz', chunksize=500000, usecols=['url', 'khatadari'])):

11
12

<ipython-input-30-22995dd2d7fb>:12: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df in enumerate(pd.read_csv('rights.csv.gz', chunksize=500000, usecols=['url', 'khatadari'])):

13

<ipython-input-30-22995dd2d7fb>:12: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df in enumerate(pd.read_csv('rights.csv.gz', chunksize=500000, usecols=['url', 'khatadari'])):

14
15

<ipython-input-30-22995dd2d7fb>:12: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df in enumerate(pd.read_csv('rights.csv.gz', chunksize=500000, usecols=['url', 'khatadari'])):

16

<ipython-input-30-22995dd2d7fb>:12: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df in enumerate(pd.read_csv('rights.csv.gz', chunksize=500000, usecols=['url', 'khatadari'])):

17
18
19
20
21

<ipython-input-30-22995dd2d7fb>:12: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df in enumerate(pd.read_csv('rights.csv.gz', chunksize=500000, usecols=['url', 'khatadari'])):

22

<ipython-input-30-22995dd2d7fb>:12: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df in enumerate(pd.read_csv('rights.csv.gz', chunksize=500000, usecols=['url', 'khatadari'])):

23

<ipython-input-30-22995dd2d7fb>:12: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df in enumerate(pd.read_csv('rights.csv.gz', chunksize=500000, usecols=['url', 'khatadari'])):

24

<ipython-input-30-22995dd2d7fb>:12: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df in enumerate(pd.read_csv('rights.csv.gz', chunksize=500000, usecols=['url', 'khatadari'])):

25

<ipython-input-30-22995dd2d7fb>:12: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df in enumerate(pd.read_csv('rights.csv.gz', chunksize=500000, usecols=['url', 'khatadari'])):

26

<ipython-input-30-22995dd2d7fb>:12: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df in enumerate(pd.read_csv('rights.csv.gz', chunksize=500000, usecols=['url', 'khatadari'])):

27

<ipython-input-30-22995dd2d7fb>:12: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df in enumerate(pd.read_csv('rights.csv.gz', chunksize=500000, usecols=['url', 'khatadari'])):

28

<ipython-input-30-22995dd2d7fb>:12: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df in enumerate(pd.read_csv('rights.csv.gz', chunksize=500000, usecols=['url', 'khatadari'])):

29

<ipython-input-30-22995dd2d7fb>:12: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df in enumerate(pd.read_csv('rights.csv.gz', chunksize=500000, usecols=['url', 'khatadari'])):

30
31
32

<ipython-input-30-22995dd2d7fb>:12: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df in enumerate(pd.read_csv('rights.csv.gz', chunksize=500000, usecols=['url', 'khatadari'])):

33

<ipython-input-30-22995dd2d7fb>:12: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df in enumerate(pd.read_csv('rights.csv.gz', chunksize=500000, usecols=['url', 'khatadari'])):

34
35
36
37
38
39

<ipython-input-30-22995dd2d7fb>:12: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df in enumerate(pd.read_csv('rights.csv.gz', chunksize=500000, usecols=['url', 'khatadari'])):

40

<ipython-input-30-22995dd2d7fb>:12: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df in enumerate(pd.read_csv('rights.csv.gz', chunksize=500000, usecols=['url', 'khatadari'])):

41
42
43
44
45
46
47
48

<ipython-input-30-22995dd2d7fb>:12: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df in enumerate(pd.read_csv('rights.csv.gz', chunksize=500000, usecols=['url', 'khatadari'])):

49

<ipython-input-30-22995dd2d7fb>:12: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df in enumerate(pd.read_csv('rights.csv.gz', chunksize=500000, usecols=['url', 'khatadari'])):

50

<ipython-input-30-22995dd2d7fb>:12: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df in enumerate(pd.read_csv('rights.csv.gz', chunksize=500000, usecols=['url', 'khatadari'])):

51

<ipython-input-30-22995dd2d7fb>:12: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df in enumerate(pd.read_csv('rights.csv.gz', chunksize=500000, usecols=['url', 'khatadari'])):

52

<ipython-input-30-22995dd2d7fb>:12: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df in enumerate(pd.read_csv('rights.csv.gz', chunksize=500000, usecols=['url', 'khatadari'])):

53

In [31]:
rdf

                   khatadari
0           3101090651000032
1           3101090651000013
2           3101090651000013
3           3101090651000058
4           3101090651000040
...                      ...
26871948  2203411371000367.0
26871949  2203411371000367.0
26871950  2203411371000433.0
26871951  2203411371002663.0
26871952  2203411371001509.0

[26871953 rows x 1 columns]

In [32]:
rdf[rdf.khatadari=='Label']

Empty DataFrame
Columns: [khatadari]
Index: []

In [33]:
rdf.drop_duplicates(inplace=True)
rdf

                   khatadari
0           3101090651000032
1           3101090651000013
3           3101090651000058
4           3101090651000040
5           3101090651000044
...                      ...
26871947  2203411371003512.0
26871948  2203411371000367.0
26871950  2203411371000433.0
26871951  2203411371002663.0
26871952  2203411371001509.0

[7859509 rows x 1 columns]

In [34]:
df = pd.read_csv('account_unique.csv.gz', usecols=['Account_Holder_No'])
df

         Account_Holder_No
0         3101090651000032
1         3101090651000013
2         3101090651000058
3         3101090651000040
4         3101090651000044
...                    ...
7859517   2203411371003512
7859518   2203411371000367
7859519   2203411371000433
7859520   2203411371002663
7859521   2203411371001509

[7859522 rows x 1 columns]

In [35]:
rdf.dropna(inplace=True)
rdf

                   khatadari
0           3101090651000032
1           3101090651000013
3           3101090651000058
4           3101090651000040
5           3101090651000044
...                      ...
26871947  2203411371003512.0
26871948  2203411371000367.0
26871950  2203411371000433.0
26871951  2203411371002663.0
26871952  2203411371001509.0

[7859508 rows x 1 columns]

In [36]:
rdf.khatadari = rdf.khatadari.astype(int)
rdf

                 khatadari
0         3101090651000032
1         3101090651000013
3         3101090651000058
4         3101090651000040
5         3101090651000044
...                    ...
26871947  2203411371003512
26871948  2203411371000367
26871950  2203411371000433
26871951  2203411371002663
26871952  2203411371001509

[7859508 rows x 1 columns]

In [37]:
mdf = df[~df.Account_Holder_No.isin(rdf.khatadari)]
mdf

         Account_Holder_No
753340    2806231228000554
762129    2806201340001065
763394    2806211521001767
767019    2806221160002187
767971    2806221106000998
772312    2806221110001466
776518    2806231211001317
776614    2806231208001099
777145    2806231210001372
779674    2806231224000892
785057    2806191190000517
789734    2806181158001021
791431    2806181134000583
796823    2806181153001193
804526    2806191201001632
806989    2806191206001344
862610    2805151021001419
877933    2805141280001064
889798    2805141246001407
891851    2805141303000455
894511    2804120684000729
905110    2804120746000617
956414    2804110666001250
961076    2803090409000964
970742    2803090389001559
1001409   2803100509000755
1020571   2803070280000518
1025598   2803080359001761
1027918   2803080327000438
1030075   2803080363001460
1039461   2802051492000621
1068150   2802040210001218
2446860   3202111348000206
2448095   3202111352000293
2483109   3202101305000458
2486656   3202101285000136
2581956   1303041158003717
2652189   1302020942001850
2686185   1303021080003606
2735239   1301080717003542
2735250   1301080717003541
2745531   1301080755002084
2751338   1301080714003278
2816194   1301060546003196
2817576   1301060599002592
2877367   1301050462005716
2888045   1301050442003104
2961498    505020959002600
3021888    504030882001599
3024874    504030884003579
3041705    503040782001238
3051096    503020674001622
3106430    502020328003185
3247121   2902110834001111
3916884    501010039002361
4039410   2901010015000123
4853055   1803141477000232
5992488    601030195000553
6051756    401010144003065
7727748   1101090379002707

In [ ]:
mdf.to_csv('missing.csv', index=False)